-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 15:36:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Abrigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Abrigo` ;

CREATE TABLE IF NOT EXISTS `Abrigo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NULL,
  `Telefone` CHAR(11) NULL,
  `Pais` VARCHAR(50) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Estado` VARCHAR(50) NULL,
  `Rua` VARCHAR(50) NULL,
  `Numero` VARCHAR(10) NULL,
  `Ong_ID` INT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Adocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adocao` ;

CREATE TABLE IF NOT EXISTS `Adocao` (
  `Animal_ID` INT NOT NULL,
  `Receptor_CPF` CHAR(11) NOT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`Animal_ID`, `Receptor_CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Animal` ;

CREATE TABLE IF NOT EXISTS `Animal` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Sexo` CHAR(1) NULL,
  `Status` TINYINT NULL,
  `Peso` DECIMAL(5,2) NULL,
  `Especie` VARCHAR(50) NULL,
  `Abrigo_ID` INT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atendimento` ;

CREATE TABLE IF NOT EXISTS `Atendimento` (
  `Animal_ID` INT NOT NULL,
  `Veterinario_CPF` CHAR(11) NOT NULL,
  `Servico` VARCHAR(200) NULL,
  `Data` DATETIME NULL,
  PRIMARY KEY (`Animal_ID`, `Veterinario_CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Captura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Captura` ;

CREATE TABLE IF NOT EXISTS `Captura` (
  `Animal_ID` INT NOT NULL,
  `Capturador_CPF` CHAR(11) NOT NULL,
  `Local` VARCHAR(200) NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`Animal_ID`, `Capturador_CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capturador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capturador` ;

CREATE TABLE IF NOT EXISTS `Capturador` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  PRIMARY KEY (`CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Departamento` ;

CREATE TABLE IF NOT EXISTS `Departamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Descricao` VARCHAR(200) NULL,
  `Ong_ID` INT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doacao` ;

CREATE TABLE IF NOT EXISTS `Doacao` (
  `Descricao` VARCHAR(200) NULL,
  `Quantia` DECIMAL(10,2) NULL,
  `Data` DATE NULL,
  `Ong_ID` INT NOT NULL,
  `Doador_ID` INT NOT NULL
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doador` ;

CREATE TABLE IF NOT EXISTS `Doador` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Telefone` CHAR(11) NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionario` ;

CREATE TABLE IF NOT EXISTS `Funcionario` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Telefone` CHAR(11) NULL,
  `Cargo` VARCHAR(50) NULL,
  `Departamento_ID` INT NOT NULL,
  `Abrigo_ID` INT NOT NULL,
  PRIMARY KEY (`CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ong` ;

CREATE TABLE IF NOT EXISTS `Ong` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Receptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receptor` ;

CREATE TABLE IF NOT EXISTS `Receptor` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Pais` VARCHAR(50) NULL,
  `Estado` VARCHAR(50) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Rua` VARCHAR(50) NULL,
  `Numero` VARCHAR(10) NULL,
  PRIMARY KEY (`CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinario` ;

CREATE TABLE IF NOT EXISTS `Veterinario` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Especialidade` VARCHAR(200) NULL,
  PRIMARY KEY (`CPF`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- ALTER TABLE: FOREIGN KEYS
-- -----------------------------------------------------

ALTER TABLE `Abrigo`
  ADD CONSTRAINT `FK_ABRIGO_ONG`
  FOREIGN KEY (`Ong_ID`) REFERENCES `Ong` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Adocao`
  ADD CONSTRAINT `FK_ADOCAO_ANIMAL`
  FOREIGN KEY (`Animal_ID`) REFERENCES `Animal` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_ADOCAO_RECEP`
  FOREIGN KEY (`Receptor_CPF`) REFERENCES `Receptor` (`CPF`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Animal`
  ADD CONSTRAINT `FK_ANIMAL_ABRIGO`
  FOREIGN KEY (`Abrigo_ID`) REFERENCES `Abrigo` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Atendimento`
  ADD CONSTRAINT `FK_ATENDIMENTO_ANIMAL`
  FOREIGN KEY (`Animal_ID`) REFERENCES `Animal` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_ATENDIMENTO_VET`
  FOREIGN KEY (`Veterinario_CPF`) REFERENCES `Veterinario` (`CPF`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Captura`
  ADD CONSTRAINT `FK_CAPTURA_ANIMAL`
  FOREIGN KEY (`Animal_ID`) REFERENCES `Animal` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_CAPTURA_CAPT`
  FOREIGN KEY (`Capturador_CPF`) REFERENCES `Capturador` (`CPF`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Departamento`
  ADD CONSTRAINT `FK_DEPT_ONG`
  FOREIGN KEY (`Ong_ID`) REFERENCES `Ong` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Doacao`
  ADD CONSTRAINT `FK_DOACAO_ONG`
  FOREIGN KEY (`Ong_ID`) REFERENCES `Ong` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_DOACAO_DOADOR`
  FOREIGN KEY (`Doador_ID`) REFERENCES `Doador` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;

ALTER TABLE `Funcionario`
  ADD CONSTRAINT `FK_FUNC_DEPT`
  FOREIGN KEY (`Departamento_ID`) REFERENCES `Departamento` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_FUNC_ABRIGO`
  FOREIGN KEY (`Abrigo_ID`) REFERENCES `Abrigo` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE CASCADE;


-- -----------------------------------------------------
-- CREATE INDEXES
-- -----------------------------------------------------

CREATE INDEX `FK_ABRIGO_ONG_IDX` ON `Abrigo` (`Ong_ID` ASC) VISIBLE;
CREATE INDEX `FK_ADOCAO_RECEP` ON `Adocao` (`Receptor_CPF` ASC) VISIBLE;
CREATE INDEX `FK_ADOCAO_ANIMAL` ON `Adocao` (`Animal_ID` ASC) VISIBLE;
CREATE INDEX `FK_ANIMAL_ABRIGO_IDX` ON `Animal` (`Abrigo_ID` ASC) VISIBLE;
CREATE INDEX `FK_ATEND_VET_IDX` ON `Atendimento` (`Veterinario_CPF` ASC) VISIBLE;
CREATE INDEX `FK_ATEND_ANIMAL_IDX` ON `Atendimento` (`Animal_ID` ASC) VISIBLE;
CREATE INDEX `FK_CAPTURA_CAPT_IDX` ON `Captura` (`Capturador_CPF` ASC) VISIBLE;
CREATE INDEX `FK_CAPTURA_ANIMAL_IDX` ON `Captura` (`Animal_ID` ASC) VISIBLE;
CREATE INDEX `FK_DEPT_ONG_IDX` ON `Departamento` (`Ong_ID` ASC) VISIBLE;
CREATE INDEX `FK_DOACAO_ONG_IDX` ON `Doacao` (`Ong_ID` ASC) VISIBLE;
CREATE INDEX `FK_DOACAO_DOADOR_IDX` ON `Doacao` (`Doador_ID` ASC) VISIBLE;
CREATE INDEX `FK_FUNC_DEPT_IDX` ON `Funcionario` (`Departamento_ID` ASC) VISIBLE;
CREATE INDEX `FK_FUNC_ABRIGO_IDX` ON `Funcionario` (`Abrigo_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Usuário de administração
-- -----------------------------------------------------

SET SQL_MODE = '';
DROP USER IF EXISTS Admin;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Admin' IDENTIFIED BY 'Admin123';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
