-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 13:30:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Abrigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Abrigo` ;

CREATE TABLE IF NOT EXISTS `Abrigo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NULL,
  `Telefone` CHAR(11) NULL,
  `Pais` VARCHAR(50) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Estado` VARCHAR(50) NULL,
  `Rua` VARCHAR(50) NULL,
  `Numero` INT NULL,
  `ID_Ong` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ABRIGO_ONG`
    FOREIGN KEY (`ID_Ong`)
    REFERENCES `Ong` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `Abrigo` (`Email` ASC) VISIBLE;

CREATE INDEX `ID_idx` ON `Abrigo` (`ID_Ong` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Adocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adocao` ;

CREATE TABLE IF NOT EXISTS `Adocao` (
  `ID_Animal` INT NOT NULL,
  `CPF_Receptor` INT NOT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`ID_Animal`, `CPF_Receptor`),
  CONSTRAINT `FK_ADOCAO_ANIMAL`
    FOREIGN KEY (`ID_Animal`)
    REFERENCES `Animal` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ADOCAO_RECEP`
    FOREIGN KEY (`CPF_Receptor`)
    REFERENCES `Receptor` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CPF_Receptor_idx` ON `Adocao` (`CPF_Receptor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Animal` ;

CREATE TABLE IF NOT EXISTS `Animal` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Sexo` CHAR(1) NULL,
  `Status` TINYINT NULL,
  `Peso` DECIMAL(5,2) NULL,
  `Especie` VARCHAR(50) NULL,
  `ID_Abrigo` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_Abrigo`
    FOREIGN KEY (`ID_Abrigo`)
    REFERENCES `Abrigo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_Abrigo_idx` ON `Animal` (`ID_Abrigo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atendimento` ;

CREATE TABLE IF NOT EXISTS `Atendimento` (
  `CPF_Veterinario` INT NOT NULL,
  `ID_Animal` INT NOT NULL,
  `Data` DATE NULL,
  `Servico` VARCHAR(200) NULL,
  PRIMARY KEY (`CPF_Veterinario`, `ID_Animal`),
  CONSTRAINT `FK_ATEND_VET`
    FOREIGN KEY (`CPF_Veterinario`)
    REFERENCES `Veterinario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ATEND_ANIMAL`
    FOREIGN KEY (`ID_Animal`)
    REFERENCES `Animal` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_Animal_idx` ON `Atendimento` (`ID_Animal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Captura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Captura` ;

CREATE TABLE IF NOT EXISTS `Captura` (
  `CPF_Capturador` INT NOT NULL,
  `ID_Animal` INT NOT NULL,
  `Local` VARCHAR(200) NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`CPF_Capturador`, `ID_Animal`),
  CONSTRAINT `FK_CAPTURA_CAPT`
    FOREIGN KEY (`CPF_Capturador`)
    REFERENCES `Capturador` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CAPTURA_ANIMAL`
    FOREIGN KEY (`ID_Animal`)
    REFERENCES `Animal` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_Animal_idx` ON `Captura` (`ID_Animal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Capturador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capturador` ;

CREATE TABLE IF NOT EXISTS `Capturador` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Departamento` ;

CREATE TABLE IF NOT EXISTS `Departamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Telefone` CHAR(11) NULL,
  `Descricao` VARCHAR(200) NULL,
  `ID_Ong` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_DEPT_ONG`
    FOREIGN KEY (`ID_Ong`)
    REFERENCES `Ong` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_idx` ON `Departamento` (`ID_Ong` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Doacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doacao` ;

CREATE TABLE IF NOT EXISTS `Doacao` (
  `ID_Doador` INT NOT NULL,
  `ID_Ong` INT NOT NULL,
  `Descricao` VARCHAR(200) NULL,
  `Quantia` DECIMAL(10,2) NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`ID_Doador`, `ID_Ong`),
  CONSTRAINT `FK_DOACAO_DOADOR`
    FOREIGN KEY ()
    REFERENCES `Doador` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DOACAO_ONG`
    FOREIGN KEY (`ID_Doador` , `ID_Ong`)
    REFERENCES `Ong` (`ID` , `ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doador` ;

CREATE TABLE IF NOT EXISTS `Doador` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Telefone` CHAR(11) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionario` ;

CREATE TABLE IF NOT EXISTS `Funcionario` (
  `CPF` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Telefone` VARCHAR(50) NULL,
  `Cargo` VARCHAR(50) NULL,
  `ID_Departamento` INT NULL,
  `ID_Abrigo` INT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `FK_FUNC_DEPT`
    FOREIGN KEY (`ID_Departamento`)
    REFERENCES `Departamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FUNC_ABRIGO`
    FOREIGN KEY (`ID_Abrigo`)
    REFERENCES `Abrigo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_idx` ON `Funcionario` (`ID_Departamento` ASC) VISIBLE;

CREATE INDEX `ID_Abrigo_idx` ON `Funcionario` (`ID_Abrigo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ong` ;

CREATE TABLE IF NOT EXISTS `Ong` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Receptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receptor` ;

CREATE TABLE IF NOT EXISTS `Receptor` (
  `CPF` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Pais` VARCHAR(50) NULL,
  `Estado` VARCHAR(50) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Rua` VARCHAR(50) NULL,
  `Numero` INT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinario` ;

CREATE TABLE IF NOT EXISTS `Veterinario` (
  `CPF` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(11) NULL,
  `Especialidade` VARCHAR(200) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS Admin;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Admin' IDENTIFIED BY 'Admin123';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
